/*
 * ColorPanel.java
 *
 * Created on 23 agosto 2008, 17.08
 */

package it.unitn.LODE.services.packaging;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JLabel;

/**
 *
 * @author  ronchet
 */
public class ColorPanel extends javax.swing.JPanel {
    private String text="";
    private Color color=null;
    /** Creates new form ColorPanel */
    public ColorPanel() {
        initComponents();
        this.setText("initialValue");
        this.setColor(new Color(0,0,0));
    }

    public ColorPanel(String s, int color) {
        stringLabel.setText(s);
        Color c=new Color(color);
        colorLabel.setBackground(c);
        initComponents();
    }

    public Color getColor() {
        return color;
    }

    public void setColor(Color color) {
        this.color = color;
        colorLabel.setBackground(color);
        this.repaint();
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
        //stringLabel.setText(text);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stringLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();

        stringLabel.setBackground(new java.awt.Color(200, 0, 0));
        stringLabel.setText("       ");
        stringLabel.setName("stringLabel"); // NOI18N
        stringLabel.setOpaque(true);
        stringLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stringLabelMouseClicked(evt);
            }
        });

        colorLabel.setText("stringa da cambiare");
        colorLabel.setName("colorLabel"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(colorLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(stringLabel)
                .addContainerGap(346, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(colorLabel)
                    .add(stringLabel))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void stringLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stringLabelMouseClicked
    JDialog d=null;
    final JColorChooser jcc=new JColorChooser(colorLabel.getBackground());
    ActionListener x=new ActionListener(){
            public void actionPerformed(ActionEvent arg0) {
                System.out.println(arg0.getActionCommand());
                System.out.println(jcc.getColor());
            }
        };
    d=JColorChooser.createDialog(this, 
            "Choose the color for "+stringLabel, // title
            true, // modal?
            jcc, // color chooser?
            x, //ActionLineter for ok
            x // Action LIstener for cancel
            );
    d.setVisible(true);
    System.out.println("hello");
}//GEN-LAST:event_stringLabelMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colorLabel;
    private javax.swing.JLabel stringLabel;
    // End of variables declaration//GEN-END:variables

}
