/*
 * IF_LecturePane.java
 *
 * Created on 10 agosto 2008, 9.26
 */

package it.unitn.LODE.gui;

import it.unitn.LODE.Models.Course;
import it.unitn.LODE.Models.ProgramState;

/**
 *
 * @author  ronchet
 */
public class CoursePane_IW extends javax.swing.JPanel {
    ProgramState programState=null;
    /** Creates new form IF_LecturePane */
    public CoursePane_IW() {
        programState = ProgramState.getInstance();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        nameValueLabel = new javax.swing.JLabel();
        dateValueLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();

        setEnabled(false);
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(235, 250));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        nameLabel.setText("Name:");
        nameLabel.setName("nameLabel"); // NOI18N

        dateLabel.setText("Year:");
        dateLabel.setName("DateLabel"); // NOI18N

        nameValueLabel.setForeground(new java.awt.Color(0, 0, 255));
        nameValueLabel.setText("<html><i><font color=\"red\">Course not defined</html>\""); // NOI18N
        nameValueLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nameValueLabel.setName("nameValue"); // NOI18N
        nameValueLabel.setPreferredSize(new java.awt.Dimension(250, 20));

        dateValueLabel.setForeground(new java.awt.Color(0, 0, 255));
        dateValueLabel.setText(" ");
        dateValueLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, null, null));
        dateValueLabel.setName("dateValue"); // NOI18N

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("CURRENT COURSE");
        titleLabel.setName("titleLabel"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nameValueLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .add(nameLabel)
                    .add(titleLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(dateLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(dateValueLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(11, 11, 11)
                .add(titleLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nameLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nameValueLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dateLabel)
                    .add(dateValueLabel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    void update() {
        String year=" ";
        String name="<html><i><font color=\"red\">Course not defined</html>";
        Course course=programState.getCurrentCourse();
        if (course!=null) {
           year=course.getYear();
           if (year==null) year=" ";

           if (course.getCourseName()!=null) name=course.getCourseName();
        }
        dateValueLabel.setText(year);
        nameValueLabel.setText(name);
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateValueLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameValueLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
