/*
 * CourseInputDialog.java
 *
 * Created on 7 giugno 2008, 22.42
 */

package it.unitn.LODE.gui;

import it.unitn.LODE.Models.Course;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 * @author  ronchet
 */
public class CourseInputDialog extends javax.swing.JDialog {
    
    Course course=null;
    int year=0;
    //CourseController controller=null;
    //LodeController lodeController=null;

    /** Creates new form CourseInputDialog */
    public CourseInputDialog(java.awt.Frame parent) {
        super(parent, true); // modal dialog
        Calendar c=new GregorianCalendar();
        year=c.get(Calendar.YEAR);
        initComponents();
    }
    
    public Course getCourse(){return course;}
    
    public void inputCourseData(){
        this.setVisible(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseNameLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        courseNameTextField = new javax.swing.JTextField();
        yearSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        courseNameLabel.setText("Course Name");
        courseNameLabel.setName("courseNameLabel"); // NOI18N

        yearLabel.setText("Year");
        yearLabel.setName("yearLabel"); // NOI18N

        okButton.setText("OK");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        courseNameTextField.setName("courseNameTextField"); // NOI18N

        yearSpinner.setName("yearSpinner");
        yearSpinner.setValue(year);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(yearLabel)
                    .add(courseNameLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(courseNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(okButton)
                            .add(yearSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(44, 44, 44)
                        .add(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(courseNameLabel)
                    .add(courseNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(yearLabel)
                    .add(yearSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(cancelButton))
                .addContainerGap())
        );

        yearSpinner.setValue(year);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
// TODO add your handling code here:
    String courseName=courseNameTextField.getText();
    if (courseName==null||courseName.equals("")) {
        JOptionPane jop=new JOptionPane(
            "Course name cannot be empty!",
            JOptionPane.WARNING_MESSAGE,
            JOptionPane.DEFAULT_OPTION);
        JDialog d=jop.createDialog(this, "Error");
        d.setVisible(true);
        return;
    }
    String year=yearSpinner.getValue().toString();
    course=new Course(courseName,year,null);
    //controller.setCourse(course);
    resetValues();
    //lodeController.cop.resume();

    //Object[] params={};
    //lodeController.executeNextAction(params);
}//GEN-LAST:event_okButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    course=null;
    resetValues();
}//GEN-LAST:event_cancelButtonActionPerformed
private void resetValues(){
    //reset values for next use;
    this.setVisible(false);
    this.courseNameTextField.setText("");
    this.yearSpinner.setValue(year);
 
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JTextField courseNameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables

}
