/*
 * ProcessLoggerWindow.java
 *
 * Created on 1 settembre 2008, 22.34
 */

package it.unitn.LODE.gui;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.text.Document;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import org.jdesktop.application.Action;

/**
 *
 * @author  ronchet
 */
public class ProcessLoggerWindow extends javax.swing.JFrame {
    private static ProcessLoggerWindow instance=null;
    public static ProcessLoggerWindow getInstance() {
        if (instance==null)
            instance=new ProcessLoggerWindow();
        return instance;
    }

    private ProcessLoggerWindow() {
        initComponents();
        postInitComponents();
    }

    private Style outStyle=null;
    private Style errStyle=null;
    private void postInitComponents(){
        outStyle = jTextArea1.addStyle("outStyle", null);
        errStyle = jTextArea1.addStyle("errStyle", null);
        StyleConstants.setForeground(outStyle, Color.BLACK);
        StyleConstants.setForeground(errStyle, Color.BLUE);
        //jTextArea1.setsetColumns(120);
        //jTextArea1.setLineWrap(true);
        jTextArea1.setPreferredSize(new Dimension(400,300));
        this.setLocation(300, 300);
    }
    /**
     * The actual (private) constructor for this class
     * It sets up the graphics, an starts two threads for reading stdio and stderr
     * from the process
     * @param p the process to which the logger is attached
     */
    private ProcessLoggerWindow(final Process p) {
        initComponents();
        postInitComponents();
    }
    // ============= GETTERS ===================================================
    public Document getDocument(){
        return jTextArea1.getDocument();
    }
    public Style getOutStyle(){
        return outStyle;
    }
    public Style getErrStyle(){
        return errStyle;
    }
    // =========================================================================
    //final Document d=jTextArea1.getDocument();
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(ProcessLoggerWindow.class, this);
        jButton1.setAction(actionMap.get("close")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButton1)
                        .add(255, 255, 255))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 330, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This is here only for testing purposes
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ProcessLoggerWindow().setVisible(true);
            }
        });
    }

    @Action
    public void close() {
        setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextArea1;
    // End of variables declaration//GEN-END:variables

}
