/*
 * SoundPanel.java
 *
 * Created on 8-mar-2009, 10.08.21
 */

package it.unitn.LODE.gui;

import it.unitn.LODE.MP.IF.gui.SoundPanelIF;
import java.awt.Color;

/**
 *
 * @author ronchet
 */
public class SoundPanel extends javax.swing.JPanel implements SoundPanelIF {

    //AcquisitionWindow aw=null;
    /** Creates new form SoundPanel */
    public SoundPanel() {
        initComponents();
        textField1.setText(" sound level");
        textField1.setEditable(false);
        textField1.setBackground(Color.BLACK);
        //aw=AcquisitionWindow.getInstance();
    }
    public final void setColor(Color c){
            textField1.setBackground(c);
            repaint();
/*
        //if (aw.getFrame().isFocused()) {
            textField1.setBackground(c);
            System.out.println(c);
            //Component focusOwner=KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner();
            //if (focusOwner instanceof javax.swing.JButton) textField1.transferFocus();
            //System.out.println(focusOwner);
            repaint();
        }  else {
                        //if (aw.getFrame().isFocused()) textField1.requestFocus(); //helps getting the job done in OpionPanes...
            Component focusOwner=KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner();
            if (focusOwner instanceof javax.swing.JButton) focusOwner.getParent().requestFocus();
            //else if (aw.getFrame().isFocused()) textField1.requestFocus();
            //System.out.println(focusOwner);
        }*/
    }
    public final void noMeter(){
            textField1.setText("-----------");// no message since audio meter does not work with DV cameras
            textField1.setForeground(Color.BLACK);
            textField1.setBackground(Color.LIGHT_GRAY);
    }

    public final void alarm(){
        //if (aw.getFrame().isFocused()) {
            textField1.setText(" NO SOUND ! ");
            textField1.setSelectionEnd(0);
            //textField1.requestFocus();
            textField1.setForeground(Color.RED);
            repaint();
            /*
        } else {
                        //if (aw.getFrame().isFocused()) textField1.requestFocus(); //helps getting the job done in OpionPanes...
            Component focusOwner=KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner();
            if (focusOwner instanceof javax.swing.JButton) focusOwner.getParent().requestFocus();
            //else if (aw.getFrame().isFocused()) textField1.requestFocus();
            //System.out.println(focusOwner);
        }*/
    }
    public final void endAlarm(){
        //if (aw.getFrame().isFocused()) {
            textField1.setText(" sound level");
            textField1.setForeground(Color.WHITE);
            textField1.setSelectionEnd(0);
            //if (aw.getFrame().isFocused()) textField1.transferFocus(); //helps getting the job done in OpionPanes...
            repaint();
        //}
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(90, 20));

        textField1.setName("textField1"); // NOI18N
        textField1.setText("textField1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(textField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(textField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables

}
