package it.unitn.LODE.MP.constants;

import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author ronchet
 */
public class LODEConstants {
    //
    public final static int SPLASHSCREEN_SECONDS=3; // seconds for showing the splashscreen 
    public final static String FS=File.separator;//"/";//
    public final static String RS="/";// Separator in resources
    public static final String jarName="LODE.jar";
    public static final int MBperHour=165; //Megabyte per hour on disk (approx. average)
    // 
    // These are fundamental definitions needed here to avoid illegal forward references
    public final static String WORKING_DIR=System.getProperty("user.home");
    private final static String LODE_HOME_DIR="_LODE"; // name of the LODE root directory
    public final static String LODE_HOME=WORKING_DIR+FS+LODE_HOME_DIR;
    public final static String LOG_FILE = LODE_HOME +FS+ "log.txt"; // log file generated by lode
    public final static String MARKER_FILE = LODE_HOME +FS+ ".isLodeRunning"; // marker to avoid execution of a second copy of LODE
    public final static String PREFS_FILE = LODE_HOME+FS+".LODE_PREFS.XML"; // Preferences file
    public final static String PARAMS_FILE = LODE_HOME+FS+".LODE_PARAMS.XML"; // Preferences file
    //
    public final static int XPOS=400; // Location of alert windows
    public final static int YPOS=200; // Location of alert windows
    // Resources
    // see this... http://littletutorials.com/2008/03/26/locating-resources-in-java/
    //public final static String RESOURCE_ROOT= FS+"Resources"+FS;
    public final static String RESOURCE_ROOT= "Resources";
    public final static String TEMPLATE_PREFIX = RESOURCE_ROOT+RS+"TemplateHTML5";
    public final static String IMGS_PREFIX = RESOURCE_ROOT+RS+"Images"+RS;
    public final static String SCRIPT_PREFIX = RESOURCE_ROOT+RS+"Scripts"+RS;
    public final static String SLIDES_DIR = "Slides";
    public final static String NO_SLIDES_DIR = "NoSlides";
    public final static String SLIDES_PREFIX = SLIDES_DIR;
    public final static String SLIDES_RES_PREFIX = RESOURCE_ROOT+RS+SLIDES_DIR+RS;
    public final static String NO_SLIDES_PREFIX = RESOURCE_ROOT+RS+NO_SLIDES_DIR+RS;
    // Directories
    public final static String COURSES_HOME = LODE_HOME+FS+"COURSES";
    public final static String TEMP_DIR = LODE_HOME+FS+"Temp"+FS;
    public final static String TEMP_DIR2 = LODE_HOME+FS+"Temp2";
    public final static String FFMPEGX_PATH = RS+RESOURCE_ROOT;//"/Applications/ffmpegX.app/"; //MAC ONLY
    public final static String FFMPEGX_RES_PATH = RS+RESOURCE_ROOT+RS+"ffmpeg.exe";//"/Applications/ffmpegX.app/"; //MAC ONLY
    public final static String FFMPEGX_FS_PATH = FS+RESOURCE_ROOT+FS+"ffmpeg.exe";//"/Applications/ffmpegX.app/"; //MAC ONLY
    //public final static String FFMPEG_COMMAND = FFMPEGX_PATH+RS+"ffmpeg.exe";//Contents/Resources/ffmpeg";  //WIN ONLY
    //public final static String FFMPEG_COMMAND = TEMP_DIR2+FS+"ffmpeg.exe";//Contents/Resources/ffmpeg";  //WIN ONLY
    public final static String FFMPEG_COMMAND = "/Applications/ffmpeg/bin/ffmpeg";
    public final static String FFMPEG_AVI_MERGE=LODEConstants.FFMPEGX_PATH+"/Contents/Resources/avimerge"; //MAC ONLY
    public final static String FFMPEG_MENCODER=LODEConstants.FFMPEGX_PATH+"/Contents/Resources/mencoder"; //MAC ONLY
    //public final static String FLVTOOL2_PATH = FFMPEGX_PATH+"Contents/Resources/flvtool2";  //MAC ONLY
    //public final static String FLVTOOL2_PATH = "/usr/bin/flvtool2";  //MAC ONLY
    //public final static String FLVTOOL2_PATH = RS+RESOURCE_ROOT+RS+"flvtool2.exe";  //WIN ONLY
    public final static String FLVTOOL2_RES_PATH = RS+RESOURCE_ROOT+RS+"flvtool2.exe";  //WIN ONLY
    public final static String FLVTOOL2_FS_PATH = FS+RESOURCE_ROOT+FS+"flvtool2.exe";  //WIN ONLY
    public final static String FLVTOOL2_PATH = TEMP_DIR2+FS+"flvtool2.exe";  //WIN ONLY
    public final static String VLC_PATH_ON_WINDOWS = "C:\\Program Files\\VideoLAN\\VLC\\vlc.exe"; //UNUSED
    public final static String VLC_PATH_ON_MAC = "/Applications/VLC.app/Contents/MacOS/VLC";
    public static String VLC_PATH = null;

    public final static String QTLIB_PATH = "/System/Library/Java/Extensions/QTjava.zip"; //MAC ONLY
    public final static String ACQUISITION_SUBDIR=FS+"Acquisition";
    public final static String DISTRIBUTION_SUBDIR=FS+"Distribution";
    public final static String SLIDES_SOURCES_SUBDIR=FS+"Slides_Sources"+FS;
    public final static String DISTRIBUTION_IMG_DIR="img";
    public final static String DISTRIBUTION_IMG_SUBDIR=FS+"content"+FS+DISTRIBUTION_IMG_DIR;
    public final static String ACQUISITION_IMG_SUBDIR=FS+"Slides"+FS;
    
    // Antonio
    public final static String ITUNESU_DISTRIBUTION_SUBDIR=FS+"iTunesuDistribution"; //Antonio
    public final static String ITUNESU_BIT_RATE="700k";// bit rate of converted video file for iPhone
    public final static String ITUNESU_FRAME_RATE="25";// frame rate of converted video file for iPhone
    public final static int ITUNESU_SLIDE_DURATION=60;// seconds of shown slide for iPhone
    public final static String SLIDES_FILE = SLIDES_DIR;
       
    // Filenames
    public final static String LOG_NAME = "Video_Slides_LOG.txt"; // used by the obsololete Logger class
    public final static String MOVIE_FILE = "movie"; // root name of the recorded movie
    public final static String MOVIE_EXTENSION = ".mp4"; // extension of the recorded movie
    public final static String SERIALIZED_COURSE="COURSE.XML"; // name of the file containing info on the course
    public final static String SERIALIZED_COURSE_PUBLICATION="COURSE_PUBLICATION.XML"; // name of the file containing info on the course
    public final static String STANDARD_WEBSITE_DIRECTORY="WEBSITE"; // standard name of the directory where the web site is created
    public final static String SERIALIZED_LECTURE="LECTURE.XML"; // name of the file containing info on the course
    public final static String TIMED_SLIDES_XML="TIMED_SLIDES.XML";
    public final static String SLIDES_XML="SLIDES.XML"; // name of the file containing info on the course
    public final static String IMAGE_SPLASH = IMGS_PREFIX + "splash.jpg"; //splash screen image file
    public final static String DATA_XML="data.xml"; // data file for distribution
    public final static String ITUNES_LECTURE_METADATA_FILENAME="itunes_lecture.xml";
    public final static String ITUNES_COURSE_METADATA_FILENAME="itunes_course.xml";

    // Message types
    public static final int MSG_WARNING=0;
    public static final int MSG_ERROR=1;
    public static final int MSG_SUGGESTION=2;
    public static final int MSG_LOG=3;
    public static final int MSG_GENERIC=5;
    public static final int MSG_DEBUG=6;
    // Dimension of the full-size slide window
    public static final int FULL_SIZE_SLIDE_WIDTH=800;
    public static final int FULL_SIZE_SLIDE_HEIGTH=600;

    
    public static final ImageIcon ICON_LODE=new ImageIcon(LODEConstants.class.getClassLoader().getResource(LODEConstants.IMGS_PREFIX + "LODE.gif"),"LODE");
    public static final ImageIcon ICON_SPLASH = new ImageIcon(LODEConstants.class.getClassLoader().getResource(LODEConstants.IMAGE_SPLASH));

/*
    public LODEConstants() {
        java.net.URL imgURL=LODEConstants.class.getResource(LODEConstants.IMGS_PREFIX + "LODE.gif");
        if (imgURL != null) {
        ICON_LODE=new ImageIcon(imgURL, "LODE");
    }*/


}
